version: '3'

networks:
  # enable connection with Traefik
  traefik:
    external: true
  # network for the app
  apps-network:

services:
  nginx:
    container_name: "senhas-example-web"
    image: nginx:stable-alpine
    depends_on:
      - php-fpm
    restart: always
    env_file:
      - ./.env
    volumes:
      # nginx conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # app files
      - ./app:/var/www/html
    networks:
      - traefik
      - apps-network
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Get the routes from http
      #- "traefik.http.routers.senhas-vieira.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.senhas-vieira.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.senhas-vieira.entrypoints=web"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.senhas-vieira.middlewares=redirect-to-https@docker"
      # Get the routes from https
      #- "traefik.http.routers.senhas-vieira-secured.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.senhas-vieira-secured.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.senhas-vieira-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.senhas-vieira-secured.tls=true"
      - "traefik.http.routers.senhas-vieira-secured.tls.certresolver=myhttpchallenge"

  php-fpm:
    container_name: "senhas-example-php"
    build:
      context: "./php"
      dockerfile: Dockerfile
    #image: php:fpm-alpine
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    #user: "${UID:-1000}:${GID:-1000}"
    #ports:
      #- "9000:9000"
    depends_on:
      - db
    networks:
      - apps-network

  db:
    container_name: "senhas-example-db"
    #image: mysql:5.7
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - apps-network
